production:
  server:     irc.example.com
  port:       6667
  nick:       redminebot
  user:       redminebot
  channel:    '#example'
  nickserv:
    nick:     NickServ
    password: yourpassword
  throttle:
    interval: 5
    count:    3

development:
  server:     irc.example.com
  port:       6667
  nick:       redminebot
  channel:    '#example'
  nickserv:
    nick:     NickServ
    password: yourpassword
  throttle:
    interval: 5
    count:    3